[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
base = "light"
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"

[global]
# Vô hiệu hóa caching để buộc Streamlit chạy lại code từ đầu
# mỗi khi khởi động, tránh lỗi từ session state cũ.
disableWatchdog = true